experiment:
  name: "panda_lab"
  seed: 42
  episodes: 3
  max_steps: 300

robot:
  control_type: "ee"
  block_gripper: false   # false = garra pode abrir/fechar (necessário para pick_and_place)
  base_position: [-0.6, 0.0, 0.0]

simulation:
  render_mode: "human"
  step_delay: 1.00
  verbose: true

scene:
  table:
    length: 1.1
    width: 0.7
    height: 0.4
    x_offset: -0.3
    lateral_friction: 1.0
    spinning_friction: 0.001

objects:
  - name: "cube_1"
    type: "box"
    size: [0.04, 0.04, 0.04]
    mass: 1.0
    initial_position: [0.03, 0.0, 0.02]
    color: [0.1, 0.2, 0.9, 1.0]
    lateral_friction: 0.8
    spinning_friction: 0.001

obstacles: []

runtime:
  command_file: "agent.yaml"              # task + policy
  goal_file:    "goals.yaml"              # goals iniciais + mudanças em tempo real
  scripts_file: "scripts.yaml"            # comandos: run_script, change_goal, change_task_mode, change_task
  poll_every_steps: 1 # checa os arquivos a cada N steps para verificar novos comandos habilitados

logging:
  output_dir: "results/panda_lab"
