simulation:
  seed: 42
  episodes: 3
  max_steps: 10
  render_mode: "human"
  step_delay: 1.00
  verbose: true

configs:
  environment_config: "environment_with_obstacle.yaml"
  target_goal_config: "target_goal.yaml"
